# Types

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

In [2]:
2 + 2

4

In [3]:
s = "hello, world"

In [4]:
x = 2
type(x)

int

In [5]:
type(s)

str

In [6]:
y = 2.2
type(y)

float

In [7]:
b = True
type(b)

bool

In [8]:
type(None)

NoneType

In [9]:
c = 'c'
type(c)

str

In [10]:
s = 2
type(s)

int

# Data Structures

In [11]:
l = [1, 2.2, "edward", True] # list
l

[1, 2.2, 'edward', True]

In [12]:
l.append(5)
l

[1, 2.2, 'edward', True, 5]

In [13]:
l[4]

5

In [14]:
d = {"key": 1, 1: "value", (1, 2): "wow"} # dictionary or dict
d[(1,2)]

'wow'

In [15]:
d["key"]

1

In [16]:
d["math314"] = "is cool"
d

{'key': 1, 1: 'value', (1, 2): 'wow', 'math314': 'is cool'}

In [17]:
t = (1, 2, 3.4)
t

(1, 2, 3.4)

# Control Flow

In [18]:
if True:
    print("yay")
else:
    print("nay")

yay

In [19]:
if l:
    print("what")

what

In [20]:
if ():
    print("ah I get it")

In [21]:
for i in range(len(l)):
    print(i, l[i])

0 1
1 2.2
2 edward
3 True
4 5

In [22]:
d.keys()

dict_keys(['key', 1, (1, 2), 'math314'])

In [23]:
d.values()

dict_values([1, 'value', 'wow', 'is cool'])

In [24]:
d.items()

dict_items([('key', 1), (1, 'value'), ((1, 2), 'wow'), ('math314', 'is cool')])

In [25]:
for k, v in d.items():
    print(k, v)

key 1
1 value
(1, 2) wow
math314 is cool

In [26]:
c = 0
while True:
    print(c)
    if c > 10:
        break
    c += 1

0
1
2
3
4
5
6
7
8
9
10
11

In [27]:
c *= 2
c /= 1.5
c **= 3
c

3154.9629629629626

In [28]:
x = 2
x **= 2
x

4

In [29]:
if False:
    print("a")
elif True:
    print("b")
else:
    print("c")

b

# Functions

In [30]:
def f(h, j = 5, k = 6):
    return h + j
f(1, j = 8)

9

In [31]:
f(1)

6

In [32]:
f(1, k = 2, j = 3)

4

In [33]:
f(2)

7

# Class

In [34]:
class Table():
    def __init__(self, num_legs = 4):
        self.legs = num_legs

    def num_legs(self):
        return self.legs

In [35]:
t = Table()
x = t.num_legs()

In [36]:
s = Table(num_legs = 7)
s.num_legs()

7

# Numpy

In [39]:
np.exp(((np.zeros(3) + 3) * 2 ) / 6)

array([2.71828183, 2.71828183, 2.71828183])

In [50]:
rng = np.random.default_rng(seed = 789427834294)
x = rng.normal(size = 10)

In [51]:
np.mean(x)

0.05685974974670359

In [52]:
np.std(x)

1.0161486486393296

In [58]:
X = rng.normal(size = (3, 5))
np.mean(X, axis = 1)

array([ 0.10255819, -0.85520091, -0.56674674])

In [59]:
np.std(X, axis = 1)

array([0.41042252, 0.72211726, 0.57281818])